[package]
name = "netutils"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "netutils"
path = "src/lib/lib.rs"

[[bin]]
name = "dhcpd"
path = "src/dhcpd/main.rs"

[[bin]]
name = "dns"
path = "src/dns/main.rs"

[[bin]]
name = "httpd"
path = "src/httpd/main.rs"

[[bin]]
name = "irc"
path = "src/irc/main.rs"

[[bin]]
name = "nc"
path = "src/nc/main.rs"

[[bin]]
name = "ntp"
path = "src/ntp/main.rs"

[[bin]]
name = "telnetd"
path = "src/telnetd/main.rs"

[[bin]]
name = "wget"
path = "src/wget/main.rs"

[[bin]]
name = "ip"
path = "src/ip/main.rs"

[dependencies]
ntpclient = { git = "https://github.com/willem66745/ntpclient-rust" }
redox_syscall = "0.1"
rustls = "0.5"
termion = "1.0"
webpki-roots = "0.6"

[target.'cfg(not(target_os = "redox"))'.dependencies]
libc = "0.2"
